using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TOOLS.DATA
{
    public class CALIBRATION
    {
        public string Name { get; set; }

        public Point Pos0 { get; set; }
        public Point Pos1 { get; set; }
        public Point Pos2 { get; set; }
        public Point Pos3 { get; set; }
    }
}
